// createInterview('Hutcheson', neighborhood, [
// ]);

// createInterview('Mike', neighborhood, [
// ]);

/* template 
createInterview('', '', [
	'What is your hometown?',
	'',
	'If you could move to another city, would you?',
	'',
	'What neighborhood do you live in?',
	'',
	'How long have you lived in Memphis? ',
	'',
	'How would you describe the City of Memphis in three words? ',
	'',
	'What were your first impressions of Memphis? ',
	'',
	'What is your current impression of Memphis? ',
	'',
	'Do you feel Memphis has improved while you have lived here? ',
	'',
	'What is your funniest story about living in Memphis? ',
	'',
	'If you could change something about Memphis, what would it be? ',
	'',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'',
	'What is your favorite thing about Memphis? ',
	''
]);
*/

createInterview('Willie', 'Southaven, MS', [
	'What is your hometown?',
	'Roland Fork, MS, in the deep delta.',
	'If you could move to another city, would you?',
	'Yes, maybe Victoria, B.C.',
	'What neighborhood do you live in?',
	'I live in Southaven, MS now',
	'How long have you lived in Memphis? ',
	'Since 1971',
	'How would you describe the City of Memphis in three words? ',
	'Funky, brilliant, and searching.',
	'What were your first impressions of Memphis? ',
	'I was really blown away as a small town kid. I was really blown away by the hustle and bustle of the stores. I had never seen that many people in one place before and I still get that feeling when I go downtown to Memphis.',
	'What is your current impression of Memphis? ',
	'I think Memphis is one of the most authentic places on the planet. ',
	'Do you feel Memphis has improved while you have lived here? ',
	'I think Memphis has improved in the sense of building for the people who want to be here.  And I know that sounds convoluted but I think that, like, for instance all the apartments that have been built down off south main, you know that area of town. The way that Midtown has grown like that. It is not exactly how I would have populated those areas , but those are the people who are available. Somebody was talking about Overton Square the other day , they called it Broverton Square, because all the bros… you go up there, there really are a lot of east Memphis and Germantown and Collierville young people who are kind of, you know, bro culture. I used to sniff at that, but those are the people who are here now.  And we do have to cater to people who want to live here.  There are so many generations of Memphians who would not come close to living downtown. But those folks will. ',
	'What is your funniest story about living in Memphis? ',
	'? I probably have 500 great stories about living in Memphis, but the one that comes to mind right now is when I first moved to Memphis, I was 21 years old. And my first job was driving a liquor delivery truck. And it was the perfect job for a young 21 year old idiot. And I got to drive all over this city. And I learned the city like the back of my hand. Because back then there were 210 liquor stores in Memphis. And so I got to know all of those neighborhoods. And I still know Memphis like the back of my hand. The best story though is I used to have to go pick up guys who hung around the parking lots of liquor stores to come help us unload boxcars of liquor. And there was this one guy I got to know, James, and James hung out in the parking lot of T & F liquors, which is Trigg and Florida over in south Memphis. He hung out in that parking lot. I got to know him and I would go over and he would be one of the guys that I would pick up for day laborer. And so one day we were unloading a boxcar of Jack Daniels half pints . You know 48 half pint bottles and you know they are very heavy and so we were doing that, unloading at it for a few hours. James leaped out of the boxcar door, he just disappeared.  I thought what are you doing? I ran over to the door and I said ‘are you alright?’ And he said “look what I found” and he had a toad. And he said, “Oh, I am praying this thing has a luck number.” So he turns the frog over and right under the frog’s mouth there was a perfect “7”. And he proceeded to tell me that toads had lucky numbers if you could find one with a lucky number then you could win at the dog track. So long story short, James and I cashed our checks at the west Memphis dog track that night, this was in 1972, spent all our money betting on number 7 all night and never won a race. So that’s Memphis. That’s my Memphis. An addendum to that story. A few months ago I was packing up; I was leaving my building in downtown Memphis for the last time.  So I was packing my things up and I found a note that James had written his girlfriend, Velma. And she hung out at the parking lot of Thomas liquors in north Memphis. And it said “Velma, I love you.” And he was not a great writer but he said “please give my friend Willie your number. I love you, James.” And I never found her so I kept the note since 1972 and I still have the note from James. I don’t know what happened to James or Velma. It was one of those Memphis… one of those Memphis things that ties me to Memphis. And that tie will never be broken.',
	'If you could change something about Memphis, what would it be? ',
	'I would get rid of the people and the situations that keep us divided, mainly racially. I would get rid of all that. Because it is the biggest shell game in the world. You know we are so capable of doing the greatest things in the world. And that’s why we are not organized in the arts like Nashville is. So all those things that keep us spinning around in the same hole. If I could get rid of those things that separate us.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'I think I would want somebody to know that I’ve always kept an eye to the future because so much of my work has dealt with things in the past and people who have made those marks for us, whether by photograph , or by writing, or films or whatever, and so I always keep that in mind so I want people to know that I loved Memphis and I loved Memphis enough to keep documenting things of our time because I think that people by having lots to look at and to listen to they’re going to be able to come to some real conclusions about who we were. ',
	'What is your favorite thing about Memphis? ',
	'I like the way that Memphians really don’t care about how people do it in other places. People used to say, “well, that’s not how they do it in New York, that’s not how they do it in LA, or something,.” There are very few places that are like that. New Orleans  is like that but certainly Memphis is one of those places. They are here doing is kind of the Memphis way. And I like that, whether it is right or wrong. You know they are not pretending in any way. I always think about what my daughter Savannah went to Los Angeles years ago. She had this dream to go live and work in Los Angeles. She went there, and this is about 7 or 8 years ago. And she had been there about a month and she said, “I gotta tell you, LA people are different from Memphis people in this way: they act like they think cool people act. They are acting like that.” She said, “Memphis people are just cool.” You know we are not looking to somebody else to say here is how I should behave, here is how I should react to things. Just Memphis people have that kinda cool. '
]);

createInterview('Keith', 'Central Gardens', [
	'What is your hometown?',
	'My hometown is Hayti, Missouri which is about 120 miles from here. But when I was growing up in the 60s and early 70s, it would take about 2 hours to drive here. Now it takes about an hour and 20 minutes because Interstate 55 was not complete. So in some ways it was a much greater distance to get there than it is now. In spite of the fact that Hayti was my hometown, Memphis was always my Mecca for us. When I say “us”, I am talking about my family. We would come here 3 or 4 times a year .',
	'If you could move to another city, would you?',
	'I wouldn’t, because if I could I guess I would have done it. And the good side of that is my wife and I have been able to do a fair amount of travel and we have been to a number of cities and communities in the United States and enjoyed most of them. But we always enjoy coming back to Memphis. And Memphis to me, it feels like home.',
	'What neighborhood do you live in?',
	'We live in Central Gardens',
	'How long have you lived in Memphis? ',
	'I moved here in 1981 and at the time I moved here I was to be a management trainee at Goldsmith’s department store, now Macy’s. It was a great experience for me. When I moved here, Goldsmith’s thought I should move out to Germantown. Somewhere out in the suburbs. I didn’t want that. I wanted to live in Midtown Memphis. I wanted sidewalks and trees. My first place to live was on Cooper and Washington, those brownstone apartments. They are still there today. The first apartment that I was shown was the apartment that sits behind Huey’s on Madison. It was quite a rude awakening and fortunately we did not end up living there. ',
	'How would you describe the City of Memphis in three words? ',
	'This may sound like a cliché, but a bit funky, a little cool, I think very authentic. I think most people in Memphis are very authentic and genuine. We have our good share of characters. I’m sure a lot of communities do. One in particular, my wife and I don’t know, we only see, when we drive out for the evening, at a certain intersection in Midtown at a bus stop there is a fellow there, we don’t know his name but we call him “the dancing man”. He’s got his headphone on and dancing and listening to whatever music and I always tell my wife, ‘I wish I could dance as good as that guy does.’  He is having so much fun. You can look around you and see all sorts of interesting people like that.  Just a few weeks ago I was driving down Union Avenue, there’s a fellow walking down the street strumming a guitar, has a cigarette hanging out of his mouth, just as happy as could be! You go, “wow!”, that’s what I like about living in Memphis. To me Memphis constantly reminds me how special it is through its people.',
	'What were your first impressions of Memphis? ',
	'First impressions I have to go to… let me give you two. My first impression was from when I was a child coming here from Missouri. At the age of 5 or 6. Again, it would take us 2 plus hours to get here because you had to go through all the small communities, around the square, and avoid all the speed traps. And we would park our car on Union Avenue where “Parking Can be Fun” is now. That used to be Brently’s. And we would park there and my Dad would put the parking brake on and I was always concerned that the car was going to roll back into the Mississippi River. But we always had lunch at Griffin’s. Great food. And we would walk down to Goldsmith’s department store which was on Main. And it was there that I rode my first escalator. And in the 50s and 60s when we would go into Goldsmith’s, one of the first questions my mother would ask is “is Elvis in town?” And the clerks would always know; it was either yes or no. There was no question. People knew whether Elvis was in town. And regardless what the answer was, we always had to do a trip to Graceland because I am sure my mother thought she was going to see Elvis standing out in the front yard. Of course, she never did. But when I moved back as a young adult, it was all positive. I loved Memphis. It was a great new world for me, moving from Jonesboro, Arkansas which is essentially a large suburb. Overton Square was still popular then. Of course it has come back since that time. You had a lot of night life, a lot of music, a lot of activity. Downtown was still a little sketchy but it was just a good experience for me, and going back to the people, I liked the people I was associated with. Going to work at Goldsmith’s was a whole ‘nother world to itself and exposed me to a lot of people and experiences I wouldn’t have had otherwise. It was all very positive.',
	'What is your current impression of Memphis? ',
	'Memphis is going through a renaissance. People assume that it has happened over night. It hasn’t; it has taken a number of years. You know that I am associated with the Wolf River Conservancy, were going a Greenway project for the City of Memphis. The vision of this project goes back to the 1970s. So here we are now in 2017, we believe that we will complete the entire project by 2020. A $50 million project, 26 miles long. Some people would say “Oh! It’s happening overnight.” It’s not; it’s been a long, long journey. I think there are a lot of stories like that in Memphis. Things have been planned, work has been done, whether you are talking about downtown redevelopment, whether you are talking about Midtown, whether you are talking about out east. Just a lot of good things coming together, living in the City which is so entrepreneurial, which drive a lot of this economic development, whether it is FedEx, whether it is Holiday Inn back in the day, whether it is AutoZone. All those corporations that we know drive the economy which of course we all have to have a reason for being here professionally. But my impression is that we are truly a renaissance city. Yes we have some issues; the biggest we all know are the poverty and the education which I think goes hand-in-hand which has led to some crime issues. Separate to that, Memphis is a great place to live. Low cost of living, rather easy to get around, getting easier all the time with bike lanes and more walking spaces and greenspaces. All very positive. I love bringing people from out of town and give them a tour of Memphis. There are some usual places you go whether it is Graceland , the Hotel Peabody, and Mud Island, things of that nature.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Absolutely. It has improved immensely. Economically there is more opportunity; people are more bullish on this city. There are always naysayers.  What I find more often than not, is what it takes is people from outside the city coming here and see all the good.  We, perhaps, see all the bad. We miss the good things; our clean drinking water is a good example. Clean water is a challenge out west, so we should not underplay what we have such as clean drinking water. ',
	'What is your funniest story about living in Memphis? ',
	'It would have been in 1987 when my wife and I had just gotten married.  We didn’t do a traditional honeymoon because we both traveled together previously. We were staying into Memphis that week and I was moving into her home. It was on a Tuesday and she wanted to go downtown and have lunch on Beale Street.  And I very reluctantly went and told her that no one goes to Beale Street for lunch on a Tuesday. But that is what she wanted to do. So we went down there to a bar that had an open air dining area that has been closed since. But it was open then and there was a railing next to the table. No one is there except the two of us. I told her no one would be here. About that time she looks over my shoulder and say “don’t look now but Ringo Starr is walking our way.”  So of course I turn around and there is Ringo Starr and Chips Momen are walking right towards us. Ringo approached us, stopped, and said “it’s a good day, isn’t it?” And all we could say was Ringo! Of course it is! Then the two of them continued to walk off. Ringo was in town making a record with Chips. So my wife always reminds me now when I don’t want to do something , about the time when I didn’t want to go to Beale Street and we saw Ringo Starr.',
	'If you could change something about Memphis, what would it be? ',
	'Sometimes the heat in August. Of course we rationalize that because we have very mild winters. Going back to that certain amount of poverty. The education system appears to be improving. I know many people in Memphis send their kids to private school because they feel forced to. But I know there are exceptions, such as Snowden.  But if I were to change anything it might be the median income in our community so everybody could enjoy all the amenities we have.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'I think I would like them to know that I am serving as the executive director of the Wolf River Conservancy and this is what I call my encore career. And in 20 years that they might look back on the work we do protecting land primarily that protects our aquifer recharge areas and someone would say that I am glad that the Wolf River Conservancy did that because see what that means to us today. That would be one thing. The other thing is that I would hope that they would look back and see whether they Googled my name and they would see things that would tell a story that perhaps in some small way that I helped make Memphis a better place than what it was when I first got here. And that I was a good person.',
	'What is your favorite thing about Memphis? ',
	'I think one of my favorite things about Memphis is the music and the people associated with the music. One night we were down at Earnestine and Hazel’s many years ago and it was 1 or 2 in the morning and there was a band called the Rhythm Hounds and they were a 7 or 8 piece band. And they started a conga line that danced through the bar and then danced out down Beale Street all the time while playing their instruments. And we were a part of the group that followed them out and then followed them back in. And of course you have Elvis. And then you have Stax. We had the good fortune to go out and have dinner with Rufus Thomas. We had dinner at Paulette’s in Overton Square we went down to BB King’s on Beale Street. We were sitting next to the stage and people wanted Rufus to get up and sing. Rufus got up and sand that night. And then they wanted him to sing Walking the Dog. He wouldn’t sing it. So Rufus sits down and I ask him why wouldn’t he sing Walking the Dog. He says “that’s my money song. I only sing that for money.” So you have those sorts of stories. The whole music in Memphis is cool and even to this day, Bruno Mars. Bruno Mars has done several songs here in Memphis that have been big hits. Bruno Mars was known as the youngest Elvis Impersonator at the age of 3 or 4. So about 25 years ago at the Airport Hilton, which no longer exists, they were doing an Elvis impersonating contest. Bruno Mars was there and we saw him and he did a great Elvis. '
]);


createInterview('Jay', 'Speedway Terrace', [
	'What is your hometown?',
	'New York City. Born in the Bronx. Grew up much of my childhood in Rockaway Beach, by the ocean. Wasn’t a typical city life. After college I moved to Park Slope, in Brooklyn, which is now the only neighborhood outside of Manhattan that is more expensive than Manhattan . It is the largest concentration of brownstones in the country. ',
	'If you could move to another city, would you?',
	' I have lived in a few other cities, but no, I wouldn’t move.',
	'What neighborhood do you live in?',
	'Right now I live in, I guess the technical name is “Speedway Terrace.” One would identify it as Crosstown. But by historic designation, it is called Speedway Terrace.  You could ask why is it called “Speedway Terrace.”  In the early 1900s, north Parkway was a dirt road. And on the weekends, the city allowed horse racing. Then, and I don’t have a date for this, the city decided to asphalt North Parkway, so they banned horse racing. ',
	'How long have you lived in Memphis? ',
	'I took a couple of breaks out of town, but I would say since mid 1983. But I have lived simultaneously in Santa Fe, NM. While in Santa Fe, I never shut my business down.  I had a brick & mortar on Union . With some exceptions, I would drive back and forth between Memphis and Santa Fe. The average trip one-way was 15 and a half hours. And I did that for years because my work in Memphis superseded my work and life in Santa Fe.',
	'How would you describe the City of Memphis in three words? ',
	'I like the energetic attitude, not only of young people that are here are committed. And a sense of commitment to the City is what rules my connection here. If I didn’t feel it, I would move on. The level of friendliness and the level of energetic commitment and a certain kind of… with all the other frustrations that people have with any city historically, I supersede that with certain people that have attitudes of great commitment to see the city evolve. Again, that for me it what really gets me going.  Many days strangers come in my door and I can’t always make it happen, there is an almost instant friendship connection.  I have an AirBNB that I run on the side. And when we have people come in, I will call up my wife and ask, “how are the kids doing?” Sometimes they are older than I am, but they are in my environment, my home, and I very much care about their experience here.',
	'What were your first impressions of Memphis? ',
	'Back in 83, I came here with maybe 4 or 5 cartons of art. I took a plane, and in those days I actually flew with cardboard cartons of art. So I came here having set up through friends in Memphis, an exhibition. When I got in town I called the place where the planned exhibition was going to be, and they informed me that the company was in bankruptcy. And my first thought was, “wouldn’t have been nice if you had called me before I made this trip here?” So I told my friends in town what happened and they made a few phone calls. That day that I got here, completely unknown to everyone but a couple of people, the college of art now was the Art Academy, they offered me a show immediately. They didn’t even know me, and I thought “wow, this town is great!”  That was my first impression.',
	'What is your current impression of Memphis? ',
	'There is more happening now, I don’t have any data, but based on articles that I have read, there are tens of billions of dollars of construction projects, in different stages, going in Memphis. So my impression is, I feel the growth, I feel the commitment, and particularly in some younger entrepreneurs, you know a lot of people criticize the millennial community, but I see some young developers who have this really terrific attitude where they are going to make something happen.  I am working on some really major projects right now; I think they are going to have fabulous impact on the City. I am extremely enthusiastic. I had a phone call this morning from someone who was bitching and moaning about how large the black community is and I was saying you got your facts wrong. They are involved in the arts and they were telling me they were thinking of moving to Atlanta. So I Googled “Atlanta Art Scene” and one of the first articles I came upon from a major art dealer in Atlanta was that it is a struggling market. See, everyone always thinks it is better somewhere else. Certainly Memphis does not have the quantity of art galleries that Atlanta does and not even close to the quantities of galleries that Santa Fe has. But Santa Fe, NM is beyond challenged right now.  But I am encouraged, I have been invited to be in a young entrepreneur’s group, and clearly much older than anyone else involved,  I’ve also been invited on several occasions to be a part of African American art-related groups, a funny aside, The Civil Rights Museum folks , maybe a decade or so ago, came to see me because they knew my work with the black community that they made me an honorary black man.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Yeah, some people think it has been a radical improvement, I have been here long enough, and I have been in and out, that to me, what is happening now, though maybe technically wrong, it doesn’t feel gigantically different to me.  I mean I came here as a New York City kid and everyone aid that “you must have felt culture shock.” No, I really felt I fit in. So I think the numbers in the black community has gone up a little, I think in the 80s it was close to 50 percent, now it is 63 I think. So it didn’t feel to me like the City was going nowhere and suddenly there was this spike. I think it has been moving slowly. And I am positive about what I see. ',
	'What is your funniest story about living in Memphis? ',
	'I could say being made an honorary black man.  Well maybe this is not a funny story.  Let me share this one quick aside. I have a dear friend in the black community who owns maybe half a dozen shoe-shine operations. He is kind of a mobile guy, he has a couple of permanent places. And so several years back I had an exhibition at Leadership Memphis on south Main.  So I invited my friend, I asked him if he could bring a double set-up for shoe shine. I am going to pay you for the evening, but I am going to offer complimentary shoe-shines. And it was really quite phenomenal. But somebody later said to me “weren’t you concerned that it might be seen as a racist thing?” “Black man, shoe-shine” I said #1 the history of shoe-shining came from London, #2 my friend supports his family of four or five kids, he has five locations, he has a web site, he has a Youtube video with commentary from some from the African American community politicians in town. I said there is no shame there, he is doing what he is very good at. So I am blessed to have his friendship and to have some fun by saying come to an art opening and have a complimentary shoe-shine. The lead in from Leadership Memphis is that my year was 2002. It was an interesting year because it was post-911 and it was still on everyone’s psyche. Ours was the best class, ever. So every month we had different field trips. One trip we went to some old industrial complex, one of the discussions was about the history of the Pinch District. At some point they talked about the history of Jews in the Pinch District. After that session ended, there was a Q&A and black lady asked “Just what does a Jew look like? So I stood up and did a 360. That afternoon, all the black women wanted to have lunch with me. How could I have not stood up? I already knew that I was the token Jew in this class of 2002.',
	'If you could change something about Memphis, what would it be? ',
	'If Memphis had an ocean. I know it has a river. If Memphis had an ocean and mountains. I live on North Parkway and I overlook the Crosstown building. So I say the building is my skyscraper (my NY connection), it is my mountain (that is the Santa Fe connection) and the river is my ocean. So I found my peace in that little part of town. I even said this; my first regular commercial gallery space was in Cooper Young in 1989. What is now DKDC was my first gallery. And the Beauty Shop was a functioning Beauty Shop and I felt like I had moved to Mayberry. There were no restaurants. Steve Crumps Café Ole was his woodworking studio. There was very little here but I had a feeling about the neighborhood.  I am working on a very large project, so if I could have changed something I would have tried harder to have started the project a decade ago. The head of my board is the head of Latino Memphis. Their community is suffering. And part of my project is a multi-cultural research center. With a slight focus on African American and Latino art forms and culture. And so there will be a lot of opportunities for people of those communities to actively share and learn about their own cultural past. I am also linked to the University of Memphis and the African American studies. Earnestine Jenkins is a brilliant woman and is the head of African Studies at the University. And the University is having meetings about creating curriculum and potentially new degree programs based on what I am bringing to the City. That is pretty exciting.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'That I am tenacious, determined, and a word that came up a few weeks ago, steadfast. It came to me through a friend who is a Reike master. So she share this entity that came into her life. I was taking a trip to look at an important collection that I need to have.  And she said that she has this entity and could I send him on this trip with you? When I got back from the trip, I told her that this entity only said one word to me. There was no discussion, no laughing, no playfulness, it was just a kind of quietude and then he said one word, “steadfast.” ',
	'What is your favorite thing about Memphis? ',
	'It’s not the food, it’s not the elevation, it’s what I say that keeps me here. The people that I have been able to connect with. People say that new Yorkers are not friendly. You know what; I was a friendly New Yorker. I was a caring New Yorker. Once when I was younger, and stronger too, I tried to break up a fight in Santa Fe. I got kicked hard by a guy that had completely lost his mind.  We pinned him down and I put my hand on his head and told him that “this has got to end now.” I probably was not at a point when I should have been interceding, but I just had to.  And I hear people say that people in Paris are not friendly, or people in New York are not friendly. And you are not friendly unless you communicate. I never met a stranger, that has always been my profile. '
]);


/*  --------------------------------------------
------  Ronnie ---------------------- */
createInterview('Ronnie', 'Frayser', [
	'What is your hometown?',
	'Memphis, TN',
	'If you could move to another city, would you?',
	'Nope.',
	'What neighborhood do you live in?',
	'Frayser',
	'How long have you lived in Memphis? ',
	'All my life. I really enjoy this. Nice city.',
	'How would you describe the City of Memphis in three words? ',
	'Peaceful, diverse, and beautiful',
	'What was your childhood in Memphis like? ',
	'I growed up in the neighborhood. It was nice. 8 kids, 2 parents. Growed up in a single-family home. Came out pretty good.',
	'What is your current impression of Memphis? ',
	'Memphis is a lovely city. A lot going on. Pro basketball now for the city. Football team doing pretty good. So for a city it is really nice. It is a good city.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Oh yes, it has improved a whole lot since my childhood. Folks have come together now. There are more nicer folks now. More peaceful now. Folks talk to each other now. It is good.',
	'What is your funniest story about living in Memphis? ',
	'Hmm, just seeing the peoples face. Seeing the smiles on peoples faces everyday. How folks talk, how folks speak. The atmosphere. That is what it is all about, smiling.',
	'If you could change something about Memphis, what would it be? ',
	'Crime.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'That I am a good person. I respect everybody. I treated everybody right.  And hopefully I did a good thing while I was here.',
	'What is your favorite thing about Memphis? ',
	'The peoples.  That’s the thing. That’s what makes Memphis great. The peoples.'
]);

/* ---------------------------------------------------
----- Ted ------------------ */
createInterview('Ted', 'Central Gardens', [
	'What is your hometown?',
	'Knoxville, Tennessee',
	'If you could move to another city, would you?',
	'No',
	'What neighborhood do you live in?',
	'Central Gardens',
	'How long have you lived in Memphis? ',
	'Since 1992.',
	'How would you describe the City of Memphis in three words? ',
	'Inviting, relaxing, and marvelous.',
	'What were your first impressions of Memphis? ',
	'My first impression was it was just amazing.  When I first came to Rhodes as a prospective student it was St. Patrick’s Day and I remember standing in Overton Square with it being blocked off from Huey’s east through the square and I just thought where I grew up in Knoxville Tennessee there is not a setting like this in my first eighteen years there and I had just been to Memphis for one day and thought this is great. This would have been in 1985. ',
	'What is your current impression of Memphis? ',
	'Our City has some issues but some issues that not every big city has. If you are going to live in a metropolitan area, a top 25 city, you are going to have some crime but so much about Memphis’s history is written about the color of people’s skin and race I just wish that that would erode and go away.  And we would build the future of the City on what is positive and happening now. I take such pride; I look at Crosstown  and I see what is going in there and that building was vacant when I came to Rhodes. When you think of a building being vacant for thirty years and then takes the interest to put businesses in and the YMCA and apartments I think it is just going to be another center for people to congregate and every business will be there reacting and supporting the others.  That is what our City needs.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Yes! In lots of ways. When I came to Memphis 35 years ago I think we have improved in regards to neighborhoods, people looking out for their neighbor and not living in a kind of backyard community. People live in their front yards, they’re visible to their neighbor, they’re helping whether its mowing their grass or helping them cut down some limbs. I just think there is more of a community in one’s neighborhood that there may not have been.  I think most are now.',
	'What is your funniest story about living in Memphis? ',
	'When I first came to Rhodes it was something like the feeling of going from middle school to high school.  There were these urban legends; when I was an eight-grader there was an urban legend that there was a smoking pit behind my classroom that underclassmen were thrown into it and beaten up before I went to high school.  So there were some nerves. When I left Knoxville Tennessee , a city of two hundred thousand to move to Memphis, a city which was obviously the largest metropolitan area in Tennessee, you know Rhodes is an urban campus so one of my first weeks on campus the closest place off campus to cash a check or get soda or a beer, it is an Exxon now but it used to be a 7-11. And I can remember stories of freshman at Rhodes going to the 7-11 and people coming up to them and asking if they wanted to buy this VCR. It would be a VCR box and one of my classmates was offered a VCR for $15 or $20 and they bought this VCR and they get it home and it was just a box of rocks. And that was my first impression of Memphis was that I was just too naïve to leave the walls of Rhodes College because it was a metropolitan city. Whenever I am approached by someone, which happens very often in the City, asking for money or trying to sell you something, you know you have to have city wits to live in the area. ',
	'If you could change something about Memphis, what would it be? ',
	'Well both of my daughters went to private schools. So if there is anything I can change about Memphis , but the stereotype when people come to Memphis is that they are told immediately that they not need to live in the inner city and that they need to join the white flight into Germantown or Collierville and they are told that our school system sucks. But I hear great stories about White Station. And when you consider the cost of private schools for fifteen years that is an extreme burden on the middle class that you have no viable public school options. So if I could change something about Memphis, and bring three hundred thousand dollars back to my wallet I would make the public schools in Memphis like the public school available in other communities. ',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'I would like for them to know that I was a proud Memphian and that I would do anything to look after and protect my neighbor and an honest and sincere person who would do anything for my neighbor and friend.',
	'What is your favorite thing about Memphis? ',
	'I love the food!  I love Memphis food.  When I used to live in Greensboro, North Carolina I daydreamed about a Huey’s hamburger or a Rendezvous rib or a Gibson’s doughnut or a Gus’s fried chicken. I just think that Memphis has the most incredible food from places that are total hole in the walls to best dining.  My fiancé’s friends, when they come from New York they go to Tsunami and they think Tsunami is one of the best restaurants in the country. My favorite things about Memphis are the people and the places I can eat.'
]);

createInterview('Karen', 'East Memphis', [
	'What is your hometown?',
	'Merida, Yucatan, Mexico',
	'If you could move to another city, would you?',
	'At this point, I would not consider it.',
	'What neighborhood do you live in?',
	'East Memphis',
	'How long have you lived in Memphis? ',
	'3 or 4 years',
	'How would you describe the City of Memphis in three words? ',
	'Vibrant, diverse,  unique',
	'What were your first impressions of Memphis? ',
	'I was told about Memphis.  I never settle for what someone told me. I was told that Memphis was a criminal city, a dirty city, and it was a very bad city. SO I started studying about its uniqueness.  It was fascinating the way in which the city was built.  It has so much history and diversity and it is beautiful. ',
	'What is your current impression of Memphis? ',
	'This is the land of opportunity.  You can meet people who have completely nothing in common who live near each other. I think that is fascinating. Because they do not cross paths. ',
	'Do you feel Memphis has improved while you have lived here? ',
	'Definitely. No doubt.  I have seen people merging more. Caring more.  I have noticed a sense of identity with this whole 901 movement.  You choose to stay in Memphis.  There are a lot of people that I know who chose to stay in this area.',
	'What is your funniest story about living in Memphis? ',
	'OK, funny?  If you like tragedy, that would be funny.  I had a car accident and afterwards I had to get downtown. I didn’t have any money because I had lost my purse. The only thing that I had was my cell phone. So I had to be downtown by 8am, I literally had just a few coins left in my house. So I had to walk a couple of miles to get access to my money but I couldn’t because I didn’t have any ID. But I noticed that a bus was passing in front of Walgreen’s. But I didn’t know how to use it.  The bank guard was super kind and he gave me a little money for the bus.  I had to ask people to help but I got on the bus.  But that day was funny and tragic because all these people helped me.  And someone gave me a free ticket. So I did spend the money and gave the ticket to a lady who had a baby so she could get on the bus.  So it all worked beautifully.  I don’t know if it is a funny story but I can tell you that I truly enjoyed it and enjoyed the ride. So all the things that people had told to me that Memphis was horrible and people are dangerous, but it all was quite beautiful.  And I thought it was funny that I had to walk in the rain, ask people for money, and it all worked out.',
	'If you could change something about Memphis, what would it be? ',
	'I would make people appreciate where they live. Take pride in that.  This is my city. For one way or another we are here, so let’s try to make it a better place.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'What would you like someone twenty years from now who reads this to know about you? That I never gave up.  No matter what.  You can make this world a better place if you just keep on doing.  Never give up.',
	'What is your favorite thing about Memphis? ',
	'The way I feel about it. I feel at home.  I feel safe here. Which is weird because everyone else feels different.  I feel that I have made a home out of a completely foreign land. I just feel embraced and appreciated and loved and I am very grateful for that.'
]);

createInterview('Kandra', 'Central Gardens', [
	'What is your hometown?',
	'West Brach, Iowa.  A very small town.',
	'If you could move to another city, would you?',
	'If I didn’t have any entanglements, yes. ',
	'What city?',
	'I loved my time in Spain. I have also been very interested in Belize and Costa Rica just because of the difference in culture and difference in priorities that people have.  And I love the climate; that Cost Rica has 3 of the 5 biomes in that tine county. Maybe somewhere far away where I could experience something completely different.',
	'What neighborhood do you live in?',
	'Central Gardens',
	'How long have you lived in Memphis? ',
	'20 years.',
	'How would you describe the City of Memphis in three words? ',
	'Progressing, tough, and BBQ',
	'What were your first impressions of Memphis? ',
	'When we visited to move here someone said it was like a big country town. So when we drove down Union,  and the streets were so wide. It was not like Chicago. There was a certain amount of space that I wasn’t used to in a city .  I was really surprised by the amount of trees. But also seeing the run-down aspects of it because we stayed  on Union and we went by Overton Square and it was crazy and very run-down. And we ended up moving like two blocks away. So my first impressions were that it needed some love. But also there was a diversity … there was just something interesting about it. Something that draws you in.  It is friendly yet very clearly not perfect but you kind of love it because it is not perfect.',
	'What is your current impression of Memphis? ',
	'I see us becoming  more progressing. People are more aware environmentally, people are trying to promote it. That is a big difference because when I first moved here everybody that lived here put down Memphis. And now, especially in the last ten years, with the Grizzlies, and people thought that would never work, then Overton Square, and the City putting money into areas where people are starting to take pride in the City and pushing the City to be more progressive.  But right now I love it because it is offering a lot that it didn’t offer even ten years ago.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Tremendously ',
	'What is your funniest story about living in Memphis? ',
	'When we first came here we visited Graceland because, you know, because it is what you do. And I grew up with Elvis, my Mom played a lot of Elvis. But I think it was when I found that they celebrate Elvis birth week and Elvis death week were these huge, and we were celebrating him dying. We have the January and the August; the death and the life and how seriously people take it with the candlelight vigil. I find it very charming. I don’t find it embarrassingly funny , I find it a charming thing.',
	'If you could change something about Memphis, what would it be? ',
	'I would like to see develop in the areas that really need it. As much as I love the kind of money the City has thrown into like uptown and downtown and Overton Square, just the amount of poverty here is frightening. So for me it would be a way to create some balance to where it is not the haves and have-nots so much because that is a huge problem for Memphis.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'Being from Iowa, from the north, the South always held a certain lore for me. Something about the southern belle, the southern drawl, the food, the pace, there were lots of things that held a certain lore that moving here and seeing the reality of life here, it is different being a northerner and now being a southerner  has changed my perspective. I am raising southerners. SO my views on what it was before and what it actually is , it has sort of exceeded my expectations because we have come so far. So something about me is that you can be from somewhere and do a 180 in your life and really benefit greatly from it and for me that was a very positive thing.',
	'What is your favorite thing about Memphis? ',
	'The people.  I’ve met a lot of very interesting people and being an instructor at the Kroc has allowed me to meet people I would never meet  because it is a real community. Socially integrated which is what they wanted when they created it.  So I would never have been able to meet them and yet we all get on well. I think people have become friends that I would never have known before. There are just a lot of really wonderful people in the world and in Memphis I seem to have found a lot of them.'
]);

createInterview('Linley', 'Cooper Young', [
	'What is your hometown?',
	'Memphis',
	'If you could move to another city, would you?',
	'Another city would have to offer an awful lot.  It would have to be a very historic place. ',
	'If so, what city?',
	'Portland, OR. Two of my friends moved there and said it was like Cooper-Young, but the whole place.',
	'What neighborhood do you live in?',
	'Cooper Young',
	'How long have you lived in Memphis? ',
	'My whole life.',
	'How would you describe the City of Memphis in three words? ',
	'Gritty, Creative , but most of all, cool.',
	'What was your childhood in Memphis like?',
	'I didn’t have that many friends, so I was lonely. I grew up in Binghampton. But before Binghampton was a cool place. So it was pretty working class, but lots of walking around and riding bikes. Mom giving me $2 and my sister and I walking to the convenience store on Poplar and buying a whole bag full of candy. And going sometimes to the jazz festival downtown.  I remember seeing Rufus Thomas playing with his shorts and platform shoes and all that. ',
	'What is your current impression of Memphis? ',
	'Its got grit. It certainly is not perfect, but we are not all in denial of the problems.  We embrace the problems along with the good and say ”that is so Memphis.” So I think we are at the point where  we are really seeing the things that we could and should do to help lift everyone up because that is going to make the City even better.  We are a strong city but people don’t know that.  We are the underdog and those of us who root for underdogs have always rooted for it.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Oh, greatly.  Yes.',
	'What is your funniest story about living in Memphis? ',
	'I used to work at Elmwood cemetery and one day, the gold cart that my friend Jodie and I were driving, blew up. The battery overheated, caught fire, and blew up. We noticed the seat was getting very hot and smelled smoke.  We ran for help and while asking someone to borrow their cell phone, the golf cart blew up. Fortunately nobody was hurt.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'I have always been a cheerleader for this city. I have always tried to work in the most interesting places here.  Which to me are those places that really embody and communicate the history of Memphis because the history of Memphis is much more interesting than people give it credit for.  And I think a lot of people somehow see Memphis as being devoid of history. Memphis has an incredibly interesting history.  Or they just pick out the bad parts. And so I have always been drawn to working at these places to really try to bring the history of Memphis alive for people so they feel that they actually do have a connection to it. So I think a lot of people in Memphis see themselves as having a limited connection to it. And it is because so many people don’t know how they fit into it.  And I think it is a lot less true now than it used to be.',
	'What is your favorite thing about Memphis? ',
	'Midtown.  I love that I go out places and see people I know. '
]);

createInterview('Golightly', 'Cooper Young', [
	'What is your hometown?',
	'Mobile, AL',
	'If you could move to another city, would you?',
	'Probably but would want to go somewhere internationally.',
	'If so, what city?',
	'No place in particular.',
	'What neighborhood do you live in?',
	'Cooper Young',
	'How long have you lived in Memphis? ',
	'Since 1987.',
	'How would you describe the City of Memphis in three words? ',
	'Southern Grit Special I like the whole idea of the southern grits and the grit, and it’s like the special of the day.',
	'What were your first impressions of Memphis? ',
	'Moved from Nashville on my own to go to Rhodes. Went for a bike ride to ride down to the river and ended up on Lamar and I thought I was about to be killed. So I rode down to the river and watched the sunset and thought this is amazing. But the ride back was scary.  So I learned from that experience that Memphis is really divided and that you had to be careful in some of them. And they were right next to each other.',
	'What is your current impression of Memphis? ',
	'Now that all seems like old hat. I try to be careful of my surroundings but I feel really safe here.  Most of the time. I have learned about the culture, the music, all the weird people that live here, so I have figured out that Memphis is slow enough that if you want to do something innovative, nobody is doing that here yet.  So if you want to shine in an area, it is easy to find an area that nobody is doing anything in. Even if it is baking rosemary cookies with caramel icing. Nobody is doing that here. And it is super cheap to live here.',
	'Do you feel Memphis has improved while you have lived here? ',
	'Oh, dramatically. I have been lucky enough to have lived here long enough to have been involved in all sorts of ways in the community. I’ve seen out east grow, education, public art, all different ways. I saw the square be great, have its demise, and then come back again.',
	'What is your funniest story about living in Memphis? ',
	'I used to work at Sun Studio as an intern and asked me to re-write their tour. I didn’t know anything about Memphis music.  There was a guy named Gary Hardy who was the owner at the time. And there was a sound engineer there named James who helped me write the tour.  So now they told me that I had to give the tour like eight times a day. That totally sucked, but the great thing about it was that these stars would come in and record there.  One day Matt Dillon came in and was very kind and agreed to pose for a picture with me.  So we were standing at the front of the store and I had my hand on the door frame and my boss came bursting in and slammed the door on my fingers. I screams and was completely appalled and embarrassed.  And cried, and then I quit. He rehired me back but I warned him that he could never do that again.',
	'If you could change something about Memphis, what would it be? ',
	'I would change the crime.  Because I would like to feel safer.',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'? I would like them to know that I am the mother of three kids.  That I direct two non-profits that I am really proud of. Memphis Reads which is a community reads project where once a year we have everyone read the book and then we have the author come to town to talk to the community and the other is Paint Memphis which is an organization which is trying to create community one wall at a time.  It is like my dream come true.  It is not painless and a lot of hard work, but the artwork will still be there and will hopefully change the face of Memphis. I want Memphis to be a destination for people to come. ',
	'What is your favorite thing about Memphis? ',
	'Maybe those Makedas cookies? Or the people.  I have made so many friends. And the grittiness.  It is not gentile but also with that southern hospitality. And if you could put that in a cookie it would be Makeda’s cookies.'
]);

createInterview('Yvonne', 'Midtown', [
	'What is your hometown?',
	'Stark, FL, I call it “prison country”. North central Florida, we have a lot of prisons there. It is a great place to move out of.',
	'If you could move to another city, would you?',
	'Yes',
	'What city?',
	'I am currently looking to relocate to St. Petersburg, FL.  I have a sailboat and I am tired of living landlocked like some kind of farmer.',
	'What neighborhood do you live in?',
	'I live in Midtown, There is no name for my neighborhood.  I am sandwiched somewhere between the Medical District and Annesdale.',
	'How long have you lived in Memphis? ',
	'17 years.',
	'How would you describe the City of Memphis in three words? ',
	'I’ll tell you what makes it hard to leave Memphis; great music everywhere, everything you want to do is close, at my business, all my metal suppliers, this is a metal city,  I am a metal artist. You can live in other places and you have to bring stuff in, we are like the transportation junction of the United States. North and South meets east and west. That’s one reason why we have great music too. We are on the road between places. And so we have such great transportation here is because we don’t have an ocean which is why I would like to leave here.  Yeah, Memphis is an interesting town, its very manageable. ',
	'What were your first impressions of Memphis? ',
	'Kind of a grimy, kind of a  gritty town. I was drawn a little bit to that. And being in the south again.  I went to college in Boston and then travelled quite a lot, around the world, I guess. I kind of liked being in the mid-South again. People are friendly again. It seemed like a good place. ',
	'What is your current impression of Memphis? ',
	'It has changed a lot.  As an artist, when I first came here people were talking about art as if it were some sort of hideous crap that costs money and no one likes. Literally that is pretty much what the City Council was saying in the late 90s. That is when they introduced 1% for art and they started building budgets for art and this city has transformed in the last 15 years.  Like downtown was a whole ‘nother place. Now there is public art everywhere. There is a lot more stuff going on. Like it feels more like a bigger city.  Things are happening and it is growing. I think my career has been carried by that. So I think it is good.  It is a very livable city. ',
	'Do you feel Memphis has improved while you have lived here? ',
	'Oh, yes.it is just a whole ‘nother city. Visually, so many places that were falling down have transformed or been renovated.',
	'What is your funniest story about living in Memphis? ',
	'There is this guy named Larry and I used to be in Cooper Young. That is where my studio was for a long time. And he always steals flowers out of people’s yards and then tries to sell them to people. He would come by my shop and want to clean up so sometimes I would give him 5 bucks and he would take the trash out. One day he shows up and tries to sell me a bicycle. And I said, it looks like my ex-boyfriend’s bicycle. So I called him and said “where’s your bicycle” and he goes “somebody stole it.”  And I said tell me exactly what it looks like. He’s like there’s a busted wheel fender on it. A beach cruiser looking. I was like, “I got it.” So I said OK Larry, I will give you $10 for this bicycle. He goes, “but I want 40”. I said “yeah, but it’s stolen.” So you either get the 10 bucks and you walk away or I call the cops  and you get a free ride somewhere. And so he struggled with the bicycle with me for a second and I called the police and then he left.  And then 3 days later he came back and apologized.',
	'If you could change something about Memphis, what would it be? ',
	'The crime is getting kind of annoying I have to say. This last weekend I got my truck broken into. Makes me kind of angry.  So I wish that, there was some.. It is getting worrisome.  Vandalism, it makes me angry. ',
	'This web site only captures a snapshot in time.  What would you like someone twenty years from now who reads this to know about you? ',
	'I guess that Memphis really gave me a chance to be an artist all the time. Which is really awesome. ',
	'What is your favorite thing about Memphis? ',
	'I am sure it is the music.  That is what makes it so hard to move back to Florida.'
]);





